import test from 'node:test';
import assert from 'node:assert/strict';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';

import { MemoryDashboard } from '../src/webview/memory/components/MemoryDashboard.js';

const translations: Record<string, string> = {
	'memory.loading': 'Загрузка...',
	'memory.runAnalysis': 'Анализировать историю',
	'memory.refresh': 'Обновить',
	'memory.dashboard.heroEyebrow': 'Память проекта',
	'memory.dashboard.heroTitle': 'Контролируйте знания о коде',
	'memory.dashboard.heroDescription': 'Следите за анализом коммитов и обновлением инструкций из одной сводки.',
	'memory.dashboard.coverage': 'Покрытие',
	'memory.dashboard.coverageSummary': 'покрытие анализом',
	'memory.dashboard.coverageFormula': '{analysed} проанализировано из {total} коммитов, сохранённых в памяти.',
	'memory.dashboard.status.analysisRunning': 'Анализ истории сейчас выполняется',
	'memory.dashboard.status.instructionsRunning': 'Очередь обновления инструкций активна',
	'memory.dashboard.status.idle': 'Сервисы памяти сейчас в ожидании',
	'memory.dashboard.instructionsCount': 'Инструкций',
	'memory.dashboard.liveBacklog': 'Живой backlog',
	'memory.dashboard.totalMemory': 'Общий объём памяти',
	'memory.dashboard.openHistories': 'Открыть истории',
	'memory.dashboard.openInstructions': 'Открыть инструкции',
	'memory.dashboard.openSettings': 'Открыть настройки',
	'memory.dashboard.metric.commits': 'Коммитов',
	'memory.dashboard.metric.commitsHelp': 'Коммиты, доступные для навигации и поиска в памяти.',
	'memory.dashboard.metric.analysed': 'Проанализировано',
	'memory.dashboard.metric.analysedHelp': 'Коммиты, для которых уже есть AI-анализ.',
	'memory.dashboard.metric.embeddings': 'Эмбеддингов',
	'memory.dashboard.metric.embeddingsHelp': 'Векторные записи для семантического поиска по памяти.',
	'memory.dashboard.metric.database': 'База',
	'memory.dashboard.metric.databaseHelp': 'Размер основной базы памяти проекта.',
	'memory.dashboard.metric.totalMemory': 'Общий объём',
	'memory.dashboard.metric.totalMemoryHelp': 'Суммарный размер памяти и хранилища инструкций.',
	'memory.dashboard.activityTitle': 'Активность анализа и использования',
	'memory.dashboard.activityDescription': 'Недавняя активность коммитов в памяти.',
	'memory.dashboard.categoriesTitle': 'Категории памяти',
	'memory.dashboard.categoriesDescription': 'Распределение коммитов по категориям.',
	'memory.dashboard.categoriesTotal': 'записей',
	'memory.dashboard.topAuthorsTitle': 'Топ авторов',
	'memory.dashboard.topAuthorsDescription': 'Самые активные авторы в памяти.',
	'memory.dashboard.hotFilesTitle': 'Горячие файлы',
	'memory.dashboard.hotFilesDescription': 'Файлы с самым частым изменением.',
	'memory.dashboard.recentTitle': 'Последние истории',
	'memory.dashboard.recentDescription': 'Последние коммиты из памяти.',
	'memory.dashboard.emptyActivity': 'Пока нет данных активности.',
	'memory.dashboard.emptyCategories': 'Пока нет категорий.',
	'memory.dashboard.emptyRecent': 'Пока нет последних историй.',
	'memory.dashboard.emptyRanking': 'Записей пока нет.',
	'memory.dashboard.commitsSuffix': 'коммитов',
	'memory.dashboard.changesSuffix': 'изменений',
};

function t(key: string): string {
	return translations[key] || key;
}

test('MemoryDashboard renders core metrics, coverage and recent commits', () => {
	const markup = renderToStaticMarkup(React.createElement(MemoryDashboard, {
		statistics: {
			totalCommits: 4,
			totalAnalyses: 3,
			totalEmbeddings: 2,
			dbSizeBytes: 1024,
			topAuthors: [{ author: 'alek', count: 3 }],
			hotFiles: [{ filePath: 'src/webview/memory/MemoryApp.tsx', count: 7 }],
			categoryDistribution: [{ category: 'frontend', count: 3 }],
			analysisModels: [{ model: 'gpt-5.4', count: 3 }],
			commitsPerDay: [
				{ date: '2026-04-10', count: 1 },
				{ date: '2026-04-11', count: 4 },
			],
		},
		recentCommits: [{
			sha: 'abcdef1234567890',
			author: 'alek',
			email: 'alek@example.com',
			date: '2026-04-18T10:00:00.000Z',
			branch: 'master',
			repository: 'prompt-manager',
			parentSha: '1234567',
			commitType: 'feat',
			message: 'Add dashboard landing page',
		}],
		codeMapStatistics: {
			totalInstructions: 8,
			totalVersions: 10,
			totalJobs: 14,
			queuedJobs: 1,
			runningJobs: 1,
			completedJobs: 12,
			failedJobs: 0,
			dbSizeBytes: 1024,
			repositories: ['prompt-manager'],
			branches: ['master'],
			latestUpdatedAt: '2026-04-18T10:00:00.000Z',
			avgDurationMs: 1000,
			avgGenerationDurationMs: 500,
			maxDurationMs: 2000,
			peakHeapUsedBytes: 4096,
			aiModels: [],
			triggerStats: [],
			repositoryStats: [],
		},
		codeMapActivity: {
			statistics: {
				totalInstructions: 8,
				totalVersions: 10,
				totalJobs: 14,
				queuedJobs: 1,
				runningJobs: 1,
				completedJobs: 12,
				failedJobs: 0,
				dbSizeBytes: 1024,
				repositories: ['prompt-manager'],
				branches: ['master'],
				latestUpdatedAt: '2026-04-18T10:00:00.000Z',
				avgDurationMs: 1000,
				avgGenerationDurationMs: 500,
				maxDurationMs: 2000,
				peakHeapUsedBytes: 4096,
				aiModels: [],
				triggerStats: [],
				repositoryStats: [],
			},
			runtime: {
				pendingCount: 0,
				queuedCount: 1,
				runningCount: 1,
				isProcessing: true,
				queuedTasks: [],
				scheduledRealtimeRefreshes: [],
				recentEvents: [],
				cycle: { queuedTotal: 2, startedTotal: 2, completedTotal: 1, failedTotal: 0 },
			},
			recentJobs: [],
		},
		analysisSnapshot: {
			status: 'running',
			effectiveLimit: 10,
			updatedAt: '2026-04-18T10:00:00.000Z',
			total: 4,
			planned: 4,
			skippedExisting: 0,
			queued: 1,
			running: 1,
			completed: 2,
			skipped: 0,
			error: 0,
			processed: 3,
			remaining: 1,
			elapsedMs: 1000,
			throughputPerMinute: 4,
			repositories: [],
			commitRows: [],
			recentEvents: [],
		},
		onOpenHistories: () => { },
		onOpenInstructions: () => { },
		onOpenSettings: () => { },
		onRunAnalysis: () => { },
		onRefresh: () => { },
		t,
	}));

	assert.ok(markup.includes('Контролируйте знания о коде'));
	assert.ok(markup.includes('75%'));
	assert.ok(markup.includes('2.0 KB'));
	assert.ok(markup.includes('Add dashboard landing page'));
	assert.ok(markup.includes('src/webview/memory/MemoryApp.tsx'));
});